from django.core.exceptions import ValidationError
import re

class CustomPasswordValidator():
    
    def __init__(self):
        pass